In [4]:
#import fasttext and numpy

import fasttext
import numpy as np

In [20]:
#load fasttext model

model = fasttext.load_model("/Users/alex/result/cc.en.300.bin")

In [53]:
#create numpy array to store word vectors

#currently set to store top 1000 words as their 100 dimensional word vectors

arr = np.ndarray(shape=(1000, 300))

In [54]:
print(arr)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [9]:
#arr[0] = [0,1,2,3,4,5,6,7,8,9]

In [55]:
print(arr)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


# Testing cosine similarity function

In [22]:
# cosine similarity of word vectors

from numpy import dot
from numpy.linalg import norm

# cos_sim = dot(a, b)/(norm(a)*norm(b))

In [26]:
vec = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
vec2 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

cos_sim = dot(vec, vec2)/(norm(vec)*norm(vec2))

print(cos_sim)

0.9962335082737976


# Get top words from dictionary

In [44]:
# Note: 1000 words from https://gist.github.com/deekayen/4148741#file-1-1000-txt

f = open("1000words/1-1000.txt", "r")

In [45]:
words = []
for i in range(0, 1000):
    words.append(f.readline())

In [46]:
print(words)

['the\n', 'of\n', 'to\n', 'and\n', 'a\n', 'in\n', 'is\n', 'it\n', 'you\n', 'that\n', 'he\n', 'was\n', 'for\n', 'on\n', 'are\n', 'with\n', 'as\n', 'I\n', 'his\n', 'they\n', 'be\n', 'at\n', 'one\n', 'have\n', 'this\n', 'from\n', 'or\n', 'had\n', 'by\n', 'not\n', 'word\n', 'but\n', 'what\n', 'some\n', 'we\n', 'can\n', 'out\n', 'other\n', 'were\n', 'all\n', 'there\n', 'when\n', 'up\n', 'use\n', 'your\n', 'how\n', 'said\n', 'an\n', 'each\n', 'she\n', 'which\n', 'do\n', 'their\n', 'time\n', 'if\n', 'will\n', 'way\n', 'about\n', 'many\n', 'then\n', 'them\n', 'write\n', 'would\n', 'like\n', 'so\n', 'these\n', 'her\n', 'long\n', 'make\n', 'thing\n', 'see\n', 'him\n', 'two\n', 'has\n', 'look\n', 'more\n', 'day\n', 'could\n', 'go\n', 'come\n', 'did\n', 'number\n', 'sound\n', 'no\n', 'most\n', 'people\n', 'my\n', 'over\n', 'know\n', 'water\n', 'than\n', 'call\n', 'first\n', 'who\n', 'may\n', 'down\n', 'side\n', 'been\n', 'now\n', 'find\n', 'any\n', 'new\n', 'work\n', 'part\n', 'take\n', 'get\n', '

In [50]:
# Remove newline '\n' from the words

correctedWords = []

for word in words:
    correctedWords.append(word.strip())

print(correctedWords)

['the', 'of', 'to', 'and', 'a', 'in', 'is', 'it', 'you', 'that', 'he', 'was', 'for', 'on', 'are', 'with', 'as', 'I', 'his', 'they', 'be', 'at', 'one', 'have', 'this', 'from', 'or', 'had', 'by', 'not', 'word', 'but', 'what', 'some', 'we', 'can', 'out', 'other', 'were', 'all', 'there', 'when', 'up', 'use', 'your', 'how', 'said', 'an', 'each', 'she', 'which', 'do', 'their', 'time', 'if', 'will', 'way', 'about', 'many', 'then', 'them', 'write', 'would', 'like', 'so', 'these', 'her', 'long', 'make', 'thing', 'see', 'him', 'two', 'has', 'look', 'more', 'day', 'could', 'go', 'come', 'did', 'number', 'sound', 'no', 'most', 'people', 'my', 'over', 'know', 'water', 'than', 'call', 'first', 'who', 'may', 'down', 'side', 'been', 'now', 'find', 'any', 'new', 'work', 'part', 'take', 'get', 'place', 'made', 'live', 'where', 'after', 'back', 'little', 'only', 'round', 'man', 'year', 'came', 'show', 'every', 'good', 'me', 'give', 'our', 'under', 'name', 'very', 'through', 'just', 'form', 'sentence', 'g

In [56]:
# Store word vectors for the 1000 words in numpy array

for i in range(0, 1000):
    arr[i] = model.get_word_vector(correctedWords[i])

# Numpy array now contains 300 dimensional vectors for top 1000 words

In [57]:
print(arr)

[[-5.17441928e-02  7.39639550e-02 -1.30568799e-02 ...  2.37025172e-01
   4.47519124e-04 -4.19306662e-03]
 [-7.30382380e-05 -1.87740743e-01 -7.10511580e-02 ...  2.84640547e-02
  -1.38433352e-01  1.80539750e-02]
 [ 4.68113739e-03  2.81242505e-02 -2.96314526e-02 ...  3.25574547e-01
  -5.08963875e-02  7.15068355e-03]
 ...
 [-8.80315602e-02 -5.49822487e-02  1.12810686e-01 ...  5.53804748e-02
  -1.32485196e-01 -1.13860920e-01]
 [-2.19269879e-02 -8.32253601e-03  6.68021813e-02 ...  6.49511516e-02
  -6.99074194e-02  5.11199329e-03]
 [ 5.16108386e-02 -1.39251962e-01 -1.99126955e-02 ...  2.07545519e-01
   5.56915104e-02 -1.66965947e-02]]


# Now conduct cosine similarity search for nearest neighbor

In [104]:
# user word
user_word = "architecture"

user_word_vec = model.get_word_vector(user_word)

# iterate through numpy array and find vector with greatest cosine similarity
index = -1
cos_sim = -1
for i in range(0, 1000):
    current = dot(user_word_vec, arr[i]) / (norm(user_word_vec) * norm(arr[i]))
    if current > cos_sim and correctedWords[i] != user_word:
        cos_sim = current
        index = i

print(correctedWords[index] + " " + str(cos_sim))

design 0.5727527782988704


## Takeaway:

### This method works great for finding related words from a known set of words. Flaws: often, top results are words that appear very close but that are not necessarily substitutes. Example: play --> game


## Thoughts: 

### Instead of using the top 1000 words, we could build a set of rare words or of words used by particular authors. Then, we could suggest a word from the set if the cosine similarity is greater than, for example, 0.7. This might help with diversification of vocabulary.

# Try searching for nearest neighbor of a sentence average word vector

In [121]:
# user sentence
user_sent = "The door mat"

user_sent_words = user_sent.split()

print(user_sent_words)

['The', 'door', 'mat']


In [122]:
vec1 = model.get_word_vector(user_sent_words[0])

vec2 = model.get_word_vector(user_sent_words[1])

vec3 = model.get_word_vector(user_sent_words[2])

In [123]:
vec4 = []
for i in range(0, 300):
    vec4.append((vec1[i] + vec2[i] + vec3[i]) / 3.0)

In [124]:
print(vec4)

[-0.018713074425856274, 0.06360449890295665, 0.0024108588695526123, 0.06884397069613139, -0.020124215632677078, -0.009119058648745218, 0.10052966078122456, 0.1822063128153483, 0.03403090685606003, 0.09781306982040405, -0.1355553368727366, -0.10854966441790263, 0.02067030469576518, -0.0815120240052541, 0.017036589483420055, 0.0835189421971639, -0.03069765865802765, -0.05021528899669647, 0.13049325346946716, -0.054400344689687095, -0.06446240842342377, 0.003913941482702891, -0.018919071803490322, 0.12124085426330566, 0.060990214347839355, -0.046024590730667114, 0.06661264598369598, -0.008052962521711985, -0.025761122504870098, 0.10611533125241597, -0.03231808046499888, 0.06738384068012238, -0.0917830765247345, -0.11673574646313985, 0.06880720953146617, 0.08545287450154622, -0.0995011826356252, 0.04878418644269308, -0.0941895842552185, -0.04328096409638723, -0.015231496344010035, 0.015798370043436687, -0.09233980377515157, 0.1338951289653778, -0.06453837454319, 0.04077438016732534, -0.072

In [125]:
user_word_vec = vec4

# iterate through numpy array and find vector with greatest cosine similarity
index = -1
cos_sim = -1
for i in range(0, 1000):
    current = dot(user_word_vec, arr[i]) / (norm(user_word_vec) * norm(arr[i]))
    if current > cos_sim and correctedWords[i] not in user_sent_words:
        cos_sim = current
        index = i

print(correctedWords[index] + " " + str(cos_sim))

floor 0.5174886243282755
